name: unit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dev dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer run-script phpunit-with-coverage

      - name: Run phpstan
        run: composer run-script phpstan

      - name: Run php-cs-fixer
        run: composer run-script php-cs-fixer

      - name: Run phpcs
        run: composer run-script phpcs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create database
        run: bin/console doctrine:database:create

      - name: Run migrations
        run: bin/console doctrine:migrations:migrate --no-interaction

      - name: Load fixtures
        run: bin/console doctrine:fixtures:load --no-interaction

      - name: Install dependencies without dev
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: bullder/textMagic:latest, bullder/textMagic:${{ github.sha }}